volumes:
  shared-ssl:

networks:
  shared-app:

services:
  ocserv_and_backend:
    restart: always
    image: ocserv_and_backend:ocserv
    container_name: ocserv_and_backend
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile.Pack
    volumes:
      - ./volumes/ocserv:/etc/ocserv
      - ./volumes/db:/app/db
      - shared-ssl:/etc/ocserv/certs
    ports:
      - ${PORT:-20443}:443/tcp
      - ${PORT:-20443}:443/udp
    env_file:
      - ./prod.env
    networks:
      - shared-app

  nginx:
    restart: always
    image: nginx:ocserv
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile.Front
    ports:
      - "880:80"
      - "8443:443"
    depends_on:
      - ocserv_and_backend
    volumes:
      - shared-ssl:/etc/nginx/certs
    env_file:
      - ./prod.env
    networks:
      - shared-app
